name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    env:
      SQL_CONNECTION_STRING: ${{ secrets.SQL_CONNECTION_STRING }}
      AAD_CLIENT_ID: ${{ secrets.AAD_CLIENT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build And Deploy
        id: swa
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: "api"
          output_location: "."
